FROM node:20 AS builder

WORKDIR /app

# Install dependencies
COPY ./my-react-app/package*.json ./
RUN npm install

# Copy source code
COPY ./my-react-app ./

# Build the production-ready app
RUN npm run build
